
POST http://localhost:5000/hirdetesek HTTP/1.1
Content-Type: application/json
Authorization: Bearer <YOUR_JWT_TOKEN>

{
  "modell": "Toyota",
  "marka": "Corolla",
  "ajtok_szama": 4,
  "hengerurtartalom": 1.8,
  "uzemanyag": "Benzin",
  "evjarat_tol": 2015,
  "evjarat_ig": 2020,
  "felhasznalo_id": 1,
  "adatok": "További részletek..."
}