### Authentication Endpoints ###

// Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "nev" : "Admin",
    "jelszo" : "Admin"
}

### 2. user számára bejelentkezés (POST)


POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "nev" : "test",
    "jelszo" : "test"
}


###

// Register Admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "nev": "Admin",
    "jelszo": "Admin",
    "email": "admin@admin.com",
    "tel": "06201234456",
    "tipus": 0
}

### 2. user létrehozása (POST)

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "nev": "test",
    "jelszo": "test",
    "email": "test@test.com",
    "tel": "06201234456",
    "tipus": 0
}

### Hirdetesek Endpoints ###

GET http://localhost:5000/hirdetesek

###

GET http://localhost:5000/hirdetesek/6

### Create a new hirdetes ###
POST http://localhost:5000/hirdetesek
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmV2IjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczOTc0NDMxMSwiZXhwIjoxNzM5NzQ3OTExfQ.Bjqc8qVzlKyr_qcQ_5tWhIZzmwOYkSvc

{
  "modell": "Teszt Modell",
  "marka": "Teszt Márka",
  "ajtok_szama": 5,
  "hengerurtartalom": 1165,
  "uzemanyag": "Benzin",
  "evjarat": 2020,
  "adatok": "Teszt adatok"
}


### Poszt létrehozása (PUT)

PUT http://localhost:5000/poszt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmV2IjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTczOTczOTY2MiwiZXhwIjoxNzM5NzQzMjYyfQ.hgbUPLe_eeRazHBhNKkFrlj3vwMKc-Q5bj_t-qRCHj8

{
    "tartalom": "Nagy barna kutya"
}

### Poszt törlése (DELETE)

DELETE   http://localhost:5000/poszt/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmV2IjoidGVzdCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTczOTczODk2MywiZXhwIjoxNzM5NzQyNTYzfQ.jKMyEaTqW4jOvSN4WZcZbO7YKCTqMwKcc6I37p8cpPc

### Poszt módosítása (PATCH)

PATCH  http://localhost:5000/poszt/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmV2IjoidGVzdCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTczOTczODk2MywiZXhwIjoxNzM5NzQyNTYzfQ.jKMyEaTqW4jOvSN4WZcZbO7YKCTqMwKcc6I37p8cpPc

{
    "tartalom": "Pacski"
}

### Posztok lekérése (GET)

GET http://localhost:5000/poszt/

### Posztok lekérése id szerint (GET)

GET http://localhost:5000/poszt/5