### Authentication Endpoints ###

// Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "nev" : "admin",
    "jelszo" : "Admin123"
}

###

// Register Admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "nev": "admin",
    "jelszo": "Admin123",
    "email": "mcisti@kaffka.com",
    "tel": "06207654321",
    "tipus": 0
}

### Hirdetesek Endpoints ###

GET http://localhost:5000/hirdetesek

###

GET http://localhost:5000/hirdetesek/6

### Create a new hirdetes ###
POST http://localhost:5000/hirdetesek
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmV2IjoiYWRtaW4iLCJlbWFpbCI6Im1jaXN0aUBrYWZma2EuY29tIiwiaWF0IjoxNzM5NzE5ODQyLCJleHAiOjE3Mzk3MjM0NDJ9.zF3OkJtkN-yvStUL_wcfBqLC8-sBeEnKUovHZ6CHiaM
Content-Type: application/json

{
    "megtekintesek": 0,
    "torles": 0,
    "adatok": "Nagy Barna kutya volt benne a centrifugában",
    "modell": "Tivoli",
    "marka": "Szángjong",
    "ajtok_szama": 5,
    "hengerurtartalom": 1.7,
    "uzemanyag": "Benzin/Gáz",
    "evjarat": 2015,
    "kep1": "na az nincs még.jpg",
    "kep2": "WÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓÓ.jpg",
    "kep3": "kep3.jpg",
    "kep4": "kep4.jpg",
    "kep5": "kep5.jpg",
    "kep6": "kep6.jpg",
    "kep7": "kep7.jpg",
    "kep8": "kep8.jpg",
    "kep9": "kep9.jpg",
    "kep10": "kep10.jpg"
}